# Generated by Django 5.2.2 on 2026-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='processed',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='source_device',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='payload',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='matched_rule',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='device',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
