# Generated by Django 5.2.2 on 2026-05-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_simplify_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
    ]
