# Generated by Django 6.0.4 on 2026-05-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('switch', 'Interruptor'), ('sensor', 'Sensor'), ('clock', 'Reloj')], max_length=16)),
                ('topic', models.CharField(max_length=255)),
                ('command_topic', models.CharField(blank=True, max_length=255)),
                ('is_registered', models.BooleanField(default=True)),
                ('current_state', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='ClockDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('increment_seconds', models.PositiveIntegerField(default=1)),
                ('rate_seconds', models.PositiveIntegerField(default=1)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('minimum_value', models.FloatField(default=20)),
                ('maximum_value', models.FloatField(default=30)),
                ('increment', models.FloatField(default=1)),
                ('interval_seconds', models.PositiveIntegerField(default=1)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='SwitchDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('state_on', models.CharField(default='ON', max_length=16)),
                ('state_off', models.CharField(default='OFF', max_length=16)),
                ('payload_on', models.CharField(default='ON', max_length=16)),
                ('payload_off', models.CharField(default='OFF', max_length=16)),
                ('failure_probability', models.FloatField(default=0.3)),
            ],
            bases=('devices.device',),
        ),
    ]
