# Generated by Django 5.2.2 on 2026-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='switchdevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='ClockDevice',
        ),
        migrations.DeleteModel(
            name='SensorDevice',
        ),
        migrations.DeleteModel(
            name='SwitchDevice',
        ),
    ]
