# Generated by Django 6.0.4 on 2026-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=255)),
                ('source_device', models.CharField(max_length=64)),
                ('operator', models.CharField(max_length=8)),
                ('threshold', models.CharField(max_length=64)),
                ('action_device', models.CharField(max_length=64)),
                ('action_value', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
