# Generated by Django 5.2.2 on 2026-05-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='action_device',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action_value',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='source_device',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='threshold',
        ),
    ]
